/** @type {import('tailwindcss').Config} */
module.exports = {
    // NOTE: Update this to include the paths to all files that contain Nativewind classes.
    content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            fontFamily: {
                'Inter-Black': ['Inter-Black'],
                'Inter-BlackItalic': ['Inter-BlackItalic'],
                'Inter-Bold': ['Inter-Bold'],
                'Inter-BoldItalic': ['Inter-BoldItalic'],
                'Inter-ExtraBold': ['Inter-ExtraBold'],
                'Inter-ExtraBoldItalic': ['Inter-ExtraBoldItalic'],
                'Inter-ExtraLight': ['Inter-ExtraLight'],
                'Inter-ExtraLightItalic': ['Inter-ExtraLightItalic'],
                'Inter-Italic': ['Inter-Italic'],
                'Inter-Light': ['Inter-Light'],
                'Inter-LightItalic': ['Inter-LightItalic'],
                'Inter-Medium': ['Inter-Medium'],
                'Inter-MediumItalic': ['Inter-MediumItalic'],
                'Inter-Regular': ['Inter-Regular'],
                'Inter-SemiBold': ['Inter-SemiBold'],
                'Inter-SemiBoldItalic': ['Inter-SemiBoldItalic'],
                'Inter-Thin': ['Inter-Thin'],
                'Inter-ThinItalic': ['Inter-ThinItalic'],

                'InterDisplay-Black': ['InterDisplay-Black'],
                'InterDisplay-BlackItalic': ['InterDisplay-BlackItalic'],
                'InterDisplay-Bold': ['InterDisplay-Bold'],
                'InterDisplay-BoldItalic': ['InterDisplay-BoldItalic'],
                'InterDisplay-ExtraBold': ['InterDisplay-ExtraBold'],
                'InterDisplay-ExtraBoldItalic': ['InterDisplay-ExtraBoldItalic'],
                'InterDisplay-ExtraLight': ['InterDisplay-ExtraLight'],
                'InterDisplay-ExtraLightItalic': ['InterDisplay-ExtraLightItalic'],
                'InterDisplay-Italic': ['InterDisplay-Italic'],
                'InterDisplay-Light': ['InterDisplay-Light'],
                'InterDisplay-LightItalic': ['InterDisplay-LightItalic'],
                'InterDisplay-Medium': ['InterDisplay-Medium'],
                'InterDisplay-MediumItalic': ['InterDisplay-MediumItalic'],
                'InterDisplay-Regular': ['InterDisplay-Regular'],
                'InterDisplay-SemiBold': ['InterDisplay-SemiBold'],
                'InterDisplay-SemiBoldItalic': ['InterDisplay-SemiBoldItalic'],
                'InterDisplay-Thin': ['InterDisplay-Thin'],
                'InterDisplay-ThinItalic': ['InterDisplay-ThinItalic'],
            },
        },
    },
    plugins: [],
};